version: '3.7'
services:
  sov-x1:
    build: .
    command: node ./app/main.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env.sow_x1
  sov-x2:
    build: .
    command: node ./app/main.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env.sow_x2
  sov-x3:
    build: .
    command: node ./app/main.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env.sow_x3
  ts5-europe-x1:
    build: .
    command: node ./app/main.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env.ts5-europe-x1